library(dplyr)
test_sub <- read.table("subject_test.txt")
x_test <- read.table("X_test.txt")
y_test <- read.table("Y_test.txt")
test_data <- cbind(test_sub, y_test)
test_data <- cbind(test_data, x_test)
names(test_data)[1] <- "sub"
names(test_data)[2] <- "y"
train_sub <- read.table("subject_train.txt")
x_train <- read.table("X_train.txt")
y_train <- read.table("Y_train.txt")
train_data <- cbind(train_sub, y_train)
train_data <- cbind(train_data, x_train)
names(train_data)[1] <- "sub"
names(train_data)[2] <- "y"
merge_data <- rbind(test_data, train_data)
extract_data <- merge_data[,c(1:8, 43:48, 83:88, 123:128, 163:168, 203,204, 216:217, 229:230, 242:243, 255:256, 268:273, 347:352, 426:431, 505:506, 518:519, 531:532, 544:545)]
extract_data$y[extract_data$y == 4] <- "SITTING"
extract_data$y[extract_data$y == 6] <- "LAYING"
extract_data$y[extract_data$y == 3] <- "WALKING_DOWNSTAIRS"
extract_data$y[extract_data$y == 2] <- "WALKING_UPSTAIRS"
extract_data$y[extract_data$y == 1] <- "WALKING"
names(extract_data)[names(extract_data) == "V1"] <- "tBodyAcc_mean_X"
names(extract_data)[names(extract_data) == "V2"] <- "tBodyAcc_mean_Y"
names(extract_data)[names(extract_data) == "V3"] <- "tBodyAcc_mean_Z"
names(extract_data)[names(extract_data) == "V4"] <- "tBodyAcc_std_X"
names(extract_data)[names(extract_data) == "V5"] <- "tBodyAcc_std_Y"
names(extract_data)[names(extract_data) == "V6"] <- "tBodyAcc_std_Z"
names(extract_data)[names(extract_data) == "V41"] <- "tGravityAcc_mean_X"
names(extract_data)[names(extract_data) == "V42"] <- "tGravityAcc_mean_Y"
names(extract_data)[names(extract_data) == "V43"] <- "tGravityAcc_mean_Z"
names(extract_data)[names(extract_data) == "V44"] <- "tGravityAcc_std_X"
names(extract_data)[names(extract_data) == "V45"] <- "tGravityAcc_std_Y"
names(extract_data)[names(extract_data) == "V46"] <- "tGravityAcc_std_Z"
names(extract_data)[names(extract_data) == "V81"] <- "tBodyAccJerk_mean_X"
names(extract_data)[names(extract_data) == "V82"] <- "tBodyAccJerk_mean_Y"
names(extract_data)[names(extract_data) == "V83"] <- "tBodyAccJerk_mean_Z"
names(extract_data)[names(extract_data) == "V84"] <- "tBodyAccJerk_std_X"
names(extract_data)[names(extract_data) == "V85"] <- "tBodyAccJerk_std_Y"
names(extract_data)[names(extract_data) == "V86"] <- "tBodyAccJerk_std_Z"
names(extract_data)[names(extract_data) == "V121"] <- "tBodyGyro_mean_X"
names(extract_data)[names(extract_data) == "V122"] <- "tBodyGyro_mean_Y"
names(extract_data)[names(extract_data) == "V123"] <- "tBodyGyro_mean_Z"
names(extract_data)[names(extract_data) == "V124"] <- "tBodyGyro_std_X"
names(extract_data)[names(extract_data) == "V125"] <- "tBodyGyro_std_Y"
names(extract_data)[names(extract_data) == "V126"] <- "tBodyGyro_std_Z"
names(extract_data)[names(extract_data) == "V161"] <- "tBodyGyroJerk_mean_X"
names(extract_data)[names(extract_data) == "V162"] <- "tBodyGyroJerk_mean_Y"
names(extract_data)[names(extract_data) == "V163"] <- "tBodyGyroJerk_mean_Z"
names(extract_data)[names(extract_data) == "V164"] <- "tBodyGyroJerk_std_X"
names(extract_data)[names(extract_data) == "V165"] <- "tBodyGyroJerk_std_Y"
names(extract_data)[names(extract_data) == "V166"] <- "tBodyGyroJerk_std_Z"
names(extract_data)[names(extract_data) == "V201"] <- "tBodyAccMag_mean"
names(extract_data)[names(extract_data) == "V202"] <- "tBodyAccMag_std"
names(extract_data)[names(extract_data) == "V214"] <- "tGravityAccMag_mean"
names(extract_data)[names(extract_data) == "V215"] <- "tGravityAccMag_std"
names(extract_data)[names(extract_data) == "V227"] <- "tBodyAccJerkMag_mean"
names(extract_data)[names(extract_data) == "V228"] <- "tBodyAccJerkMag_std"
names(extract_data)[names(extract_data) == "V240"] <- "tBodyGyroMag_mean"
names(extract_data)[names(extract_data) == "V241"] <- "tBodyGyroMag_std"
names(extract_data)[names(extract_data) == "V253"] <- "tBodyGyroJerkMag_mean"
names(extract_data)[names(extract_data) == "V254"] <- "tBodyGyroJerkMag_std"
names(extract_data)[names(extract_data) == "V266"] <- "fBodyAcc_mean_X"
names(extract_data)[names(extract_data) == "V267"] <- "fBodyAcc_mean_Y"
names(extract_data)[names(extract_data) == "V268"] <- "fBodyAcc_mean_Z"
names(extract_data)[names(extract_data) == "V269"] <- "fBodyAcc_std_X"
names(extract_data)[names(extract_data) == "V270"] <- "fBodyAcc_std_Y"
names(extract_data)[names(extract_data) == "V271"] <- "fBodyAcc_std_Z"
names(extract_data)[names(extract_data) == "V345"] <- "fBodyAccJerk_mean_X"
names(extract_data)[names(extract_data) == "V346"] <- "fBodyAccJerk_mean_Y"
names(extract_data)[names(extract_data) == "V347"] <- "fBodyAccJerk_mean_Z"
names(extract_data)[names(extract_data) == "V348"] <- "fBodyAccJerk_std_X"
names(extract_data)[names(extract_data) == "V349"] <- "fBodyAccJerk_std_Y"
names(extract_data)[names(extract_data) == "V350"] <- "fBodyAccJerk_std_Z"
names(extract_data)[names(extract_data) == "V424"] <- "fBodyGyro_mean_X"
names(extract_data)[names(extract_data) == "V425"] <- "fBodyGyro_mean_Y"
names(extract_data)[names(extract_data) == "V426"] <- "fBodyGyro_mean_Z"
names(extract_data)[names(extract_data) == "V427"] <- "fBodyGyro_std_X"
names(extract_data)[names(extract_data) == "V428"] <- "fBodyGyro_std_Y"
names(extract_data)[names(extract_data) == "V429"] <- "fBodyGyro_std_Z"
names(extract_data)[names(extract_data) == "V503"] <- "fBodyAccMag_mean"
names(extract_data)[names(extract_data) == "V504"] <- "fBodyAccMag_std"
names(extract_data)[names(extract_data) == "V516"] <- "fBodyBodyAccJerkMag_mean"
names(extract_data)[names(extract_data) == "V517"] <- "fBodyBodyAccJerkMag_std"
names(extract_data)[names(extract_data) == "V529"] <- "fBodyBodyGyroMag_mean"
names(extract_data)[names(extract_data) == "V530"] <- "fBodyBodyGyroMag_std"
names(extract_data)[names(extract_data) == "V542"] <- "fBodyBodyGyroJerkMag_mean"
names(extract_data)[names(extract_data) == "V543"] <- "fBodyBodyGyroJerkMag_std"
names(extract_data)[1] <- "subject_number"
names(extract_data)[2] <- "activity"
valid_names <- make.names(names=names(extract_data), unique=TRUE, allow_=TRUE)
names(extract_data) <- valid_names
mean_data <- summarise_each(group_by(extract_data, subject_number, activity), funs(mean))
write.table(mean_data, "step5.txt", row.name=FALSE)
